name: Deploy to Azure

on:
  push:
    branches:
      - main  # Or your chosen branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          REGISTRY: ${{ secrets.ACR_ENDPOINT }}  # Use the ACR_ENDPOINT secret
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login $REGISTRY -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker build -t $REGISTRY/my-app .
          docker push $REGISTRY/my-app
          docker logout $REGISTRY

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App for Containers
        run: |
          az webapp config container set -n proworkai -g ProWork --docker-custom-image-name $REGISTRY/my-app:latest
